<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="FormularioPersonaListarPorRut.aspx.cs" Inherits="Tanner.Web.FormularioPersonaListarPorRut" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server">
        <div class="container">
            <div  class="container-fluid">
                <h2>Buscar por Rut</h2>
                <asp:DropDownList ID="ddlPersona" AutoPostBack="True" OnSelectedIndexChanged="ddlPersona_SelectedIndexChanged" runat="server">
                </asp:DropDownList>
                <asp:Button Text="Consultar" ID="btnConsultar" runat="server" OnClick="btnConsultar_Click" />
            </div>
            <div class="container-fluid">
                <h2>Buscar por nombre</h2>
                <asp:Label Text="Ingrese nombre" runat="server" />
                <asp:TextBox ID="txtNombre" runat="server" />
                <asp:Button  Text="Buscar" ID="btnBuscar" runat="server" OnClick="btnBuscar_Click" /><br />
                <br />
                <asp:GridView ID="grdBuscar"  OnRowCancelingEdit="grdBuscar_RowCancelingEdit" OnRowEditing="grdBuscar_RowEditing" AutoGenerateColumns="false" DataKeyNames="ID" AutoGenerateEditButton="true" AutoGenerateDeleteButton="True" CssClass="table table-bordered" OnRowDeleting="grdBuscar_RowDeleting" OnRowUpdating="grdBuscar_RowUpdating" runat="server">
                    <Columns>
                        <asp:TemplateField HeaderText="Nombre">
                            <EditItemTemplate>
                                <asp:TextBox ID="TextBoxNombre" runat="server" Text='<%# Bind("Nombre") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="LabelNombre" runat="server" Text='<%# Bind("Nombre") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Apellido">
                            <EditItemTemplate>
                                <asp:TextBox ID="TextBoxApellido" runat="server" Text='<%# Bind("Apellido") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="LabelApellido" runat="server" Text='<%# Bind("Apellido") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Rut">
                            <EditItemTemplate>
                                <asp:TextBox ID="TextBoxRut" runat="server" Text='<%# Bind("Rut") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="LabelRut" runat="server" Text='<%# Bind("Rut") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>

                        <%--
                        <asp:BoundField DataField="Nombre" HeaderText="Nombre"/>
                        <asp:BoundField DataField="Apellido" HeaderText="Apellido" />
                        <asp:BoundField DataField="Rut" HeaderText="Rut" />
                        --%>
                    </Columns>
                </asp:GridView>
            </div>
        </div>
    </form>
</body>
</html>
